[package]
name = "filesystem"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
ostd.workspace = true
spin.workspace = true
thiserror = { version = "2.0.17", default-features = false }

log.workspace = true
gpt_disk_io = { version = "0.16.2", features = ["alloc"] }
lwext4_rust = { git = "https://github.com/elliott10/lwext4_rust", version = "0.2.0" }
component.workspace = true
errors.workspace = true
time.workspace = true
credentials.workspace = true
