[package]
name = "terminal"
version.workspace = true
edition.workspace = true

[dependencies]
ostd = { workspace = true }
component = { workspace = true }
spin = { workspace = true }
os-terminal = { version = "0.6.11", default-features = false, features = ["truetype"] }
log.workspace = true
filesystem = { workspace = true }
