[image]
path = "target/apk/rootfs.img"

[package]
list = []

[[files]]
source = "apps/hello.bin"
dest = "hello.bin"

[[files]]
source = "out.txt"
dest = "input.txt"

[[files]]
source = "assets/SourceCodePro.otf"
dest = "SourceCodePro.otf"
