[image]
path = "target/apk/rootfs.img"

[package]
list = [
    "musl",
    "musl-dev",
    "busybox",
    "bash",
    "readline",
    "libncursesw",
    "coreutils",
]

[[files]]
source = "apps/hello.bin"
dest = "hello.bin"

[[files]]
source = "apps/test.bin"
dest = "test.bin"

[[files]]
source = "out.txt"
dest = "input.txt"

[[files]]
source = "assets/passwd"
dest = "etc/passwd"

[[files]]
source = "assets/SourceCodePro.otf"
dest = "SourceCodePro.otf"

[[files]]
source = "assets/keep"
dest = "dev/keep"
