[workspace]
resolver = "2"
members = ["zodiac", "zodiac_macro", "builder", "kernel"]

[profile.dev]
panic = "abort"

[profile.release]
# lto = "thin"
# panic = "unwind"

# [profile.release-lto]
# inherits = "release"
lto = true
panic = "abort"
codegen-units = 1

[workspace.dependencies]
zodiac = { path = "zodiac" }
zodiac_macro = { path = "zodiac_macro" }

