[workspace.dependencies]
ostd = "0.16.1"
component = { path = "component" }
log = "0.4.28"
block = { path = "libs/block" }
driver = { path = "libs/driver" }
filesystem = { path = "libs/filesystem" }
logger = { path = "libs/logger" }
memory = { path = "libs/memory" }
task = { path = "libs/task" }
pci = { path = "libs/pci" }
errors = { path = "libs/errors" }
events = { path = "libs/events" }
credentials = { path = "libs/credentials" }
spin = "0.10.0"
bit_field = "0.10.3"
bitflags = "2.9.4"

[workspace]
exclude = ["target/osdk/base", "target/osdk/test-base"]
members = [".", "component", "component/comp-macro", "kernel", "libs/*", "modules/*"]
resolver = "3"
default-members = ["kernel"]

[workspace.package]
version = "0.1.0"
edition = "2024"
