project_type = "kernel"

[boot]
method = "grub-rescue-iso"
kcmd_args = ["ostd.log_level=TRACE\ninsmod efi_gop"]
initramfs = "target/apk/rootfs.img"

[grub]
boot_protocol = "multiboot2"

[qemu]
args = """\
    --enable-kvm \
    -machine q35 \
    -cpu host,+x2apic \
    --no-reboot \
    -m 4G \
    -smp cores=4 \
    -serial stdio \
    -drive if=pflash,format=raw,unit=0,readonly=on,file=assets/code.fd \
    -drive if=pflash,format=raw,unit=1,readonly=on,file=assets/vars.fd \
    -drive id=disk,file=target/apk/rootfs.img,if=none \
    -device ahci,id=ahci0 \
    -device ide-hd,drive=disk,bus=ahci0.0 \
    -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
    -nic user,model=e1000 \
"""
