[package]
name = "task"
version.workspace = true
edition.workspace = true

[dependencies]
ostd.workspace = true
log.workspace = true
elf = { version = "0.8.0", default-features = false }
thiserror = { version = "2.0.16", default-features = false }
bitflags.workspace = true
memory.workspace = true
filesystem.workspace = true
component.workspace = true
derive_more = { version = "2.0.1", default-features = false, features = ["full"] }
errors.workspace = true
events.workspace = true
spin.workspace = true
credentials.workspace = true
time.workspace = true
align_ext = "0.1.0"
inherit-methods-macro = "0.1.0"
int-to-c-enum = "0.1.0"
