[package]
name = "kernel"
version.workspace = true
edition = "2021"

[dependencies]
component.workspace = true
ostd.workspace = true
log.workspace = true
block.workspace = true
driver.workspace = true
filesystem.workspace = true
logger.workspace = true
memory.workspace = true
pci.workspace = true
task.workspace = true
terminal = { path = "../modules/terminal" }
ahci = { path = "../modules/ahci" }
network = { path = "../modules/network" }
nvme = { path = "../modules/nvme" }
ramdisk = { path = "../modules/ramdisk" }
