[package]
name = "zodiac_macro"
version = "0.1.0"
edition = "2024"
authors = ["Zhenjia Zeng"]
description = "Macros for zodiac"
license = "Apache-2.0"
homepage = "https://github.com/zzjrabbit/racaOS/tree/edition19/zodiac_macro"
repository = "https://github.com/zzjrabbit/racaOS"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
