[package]
name = "network"
version.workspace = true
edition.workspace = true

[dependencies]
ostd = { workspace = true }
component = { workspace = true }
log = { workspace = true }
block = { workspace = true }
bit_field.workspace = true
driver = { workspace = true }
pci = { workspace = true }
smoltcp = { version = "0.12.0", default-features = false, features = ["alloc", "log", "proto-ipv4", "proto-dhcpv4", "medium-ethernet", "socket-icmp", "socket-udp", "socket-tcp", "socket-raw", "socket-dhcpv4"] }
bitflags = "2.9.4"
spin = "0.10.0"
